import Config

# Configure your database
config :timeManager, TimeManager.Repo,
  # database: "timemanager_dev",
  # username: "postgres",
  # password: "root",
  # hostname: "localhost",
  username: System.get_env("PGUSER"),
  password: System.get_env("PGPASSWORD"),
  hostname: System.get_env("PGHOST"),
  database: System.get_env("PGDATABASE"),
  port: System.get_env("PGPORT"),
  # username: "postgres",
  # password: "root",
  # hostname: "db",
  # database: "timemanager_dev",
  # port: "5432",
  stacktrace: true,
  show_sensitive_data_on_connection_error: false,
  pool_size: 10

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :timeManager, TimeManagerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: TimeManager.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
