services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: timemanager_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - postgres
    ports:
      - "5432:5432"

  phoenix:
    build: .
    container_name: phoenix
    environment:
         # Variables to connect to our Postgres server.
         PGDATABASE: timemanager_dev
         PGUSER: postgres
         PGPASSWORD: root
         PGPORT: 5432
         # Hostname of our Postgres container.
         PGHOST: db
    # command: mix phx.server
    # Remove for production servers
    volumes:
      - ./timeManager:/app
    networks:
      - postgres
    ports:
      - "4000:4000"
    depends_on:
      - db

  vue:
    image: front:latest
    build: 
      context: ./front.Dockerfile
      # context: ./timeManager/front/Dockerfile
    # command: npm run dev
    # Remove for production servers
    # volumes:
    #   - ./timeManager/front/dist:/usr/share/nginx/html
    networks:
      - postgres
    ports:
      - "8180:80"
      # - "8180:80"
    depends_on:
      - phoenix

networks:
  postgres:
    name: postgres